#!/bin/sh

PUBLIC_DIR="/var/public"

create_public()
{
    if [ ! -d "$PUBLIC_DIR" ]; then
        mkdir -p "$PUBLIC_DIR"
        chgrp -R users "$PUBLIC_DIR"
        chmod -R 0775 "$PUBLIC_DIR"
        setfacl -m d:g:users:rwx "$PUBLIC_DIR"
        chmod g+s "$PUBLIC_DIR"
    fi
}

# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
#pre_install() {
	# do something here
#}

## arg 1:  the new package version
post_install() {
	create_public
}

## arg 1:  the new package version
## arg 2:  the old package version
#pre_upgrade() {
	# do something here
#}

## arg 1:  the new package version
## arg 2:  the old package version
#post_upgrade() {
	# do something here
#}

## arg 1:  the old package version
#pre_remove() {
	# do something here
#}

## arg 1:  the old package version
#post_remove() {
	# do something here
#}
